### PR TITLE
Check if all trafo buses are in_service and set ad_bus accordingly

### PR DESCRIPTION
**Pull request by WinfriedL**
This prevents an unsupplied ad_bus which is set in_service. Otherwise the powerflow cannot converge. I think with this #118 can be closed.

### CODE REVIEW

**Comment by lthurner** [comment]
Can you add a small test to the test suite checking this case? This fixes the problem, but also slows down the creation of the equivalent branches because of the three additional .loc operations. I think it should be possible to do this on the ppc without pandas indexing. If you add a test I can try to refactor this at some point.

**Comment by WinfriedL** [comment]
> Can you add a small test to the test suite checking this case?

So far I could not create a test which shows the problem. From what I can see the ad_bus should be set out of service in `_check_connectivity`, which works without problems in the small testcase, but seems to fail in my larger network. Or maybe there is a different issue somewhere else which I have not found yet. Which gets somehow solved by my pull request...

**Comment by WinfriedL** [comment]
Finally I have a testcase, the issue is a bit different than initially thought.

Currently `_check_connectivity()` ignores the `BR_STATUS` flag. If a three winding transformer is connected with an out of service branch to the rest of the network, the function detects it as reachable and does not set the ad_bus out of service. So my initial fix worked, because I used my own detection of out of service buses, so all three transformer buses were set out of service, and this in turn was detected by my pull request. 

I will update the pull request with a testcase and the correct fix in `_check_connectivity()`.

**Comment by lthurner** [comment]
Thanks for investigating further! I was also able to reproduce that problem in a grid without 3W-transformer, so that was really a general bug in the connectivity check. Good catch!

**Comment by WinfriedL** [comment]
> I was also able to reproduce that problem in a grid without 3W-transformer

I was assuming that this should happen without 3W transformers as well, but since I saw the problem with those, I created a testcase reflecting it. Maybe a more general testcase makes more sense...

**Pull request merged**
